sparkfabrik/spark-k8s-deployer

scripts/deploy

Skip horizontal autoscaling deployments from rollout status

Change autoscaler name

---

Dockerfile

Revert helm to 3.3.1 to avoid deployment issues and KUBECONFIG gitlab permissions warning

Revert helm to 3.3.1

---

scripts/eval-vars

It should be used like this now:
```
eval "$(scripts/env-vars PKG_DRUPAL)"
```

Just echoing the export in order to be evalueated

---

templates/jobs/pkgs/e2e_tests.yml

Fixes `Could not find package xxxx/yyyy in a version matching dev-1.7.0#b5519344c26d5e5d23c4b3f1fb01575fa9e0f537 `
when tagging

add rules for e2e pkg tests

---

scripts/helm3-init

useful for when the url is not the usual bucket

refs #000: make sparkfabrik helm chart repo url configurable

---

templates/jobs/gcloud-load-balancer-l7-cdn.yml

Using double quotas returned an error:
```
ERROR: (gcloud.compute.backend-services.update) Could not fetch resource:
155 - Invalid value for field 'resource.customResponseHeaders[0]': '"X-CDN-cache-status:{cdn_cache_status}"'. Must be a match of regex '[-!#$%&'*+.^_`|~0-9a-zA-Z]+:[	 -~]*'
```
We remove all quotas since the single quote is a permitted char as we can see in the error above.

refs platform/#2550: remove quotes in X-CDN-cache-status custom header

---

templates/.gitlab-ci-template.yml

Add env variable for Docker Dind Service.
Github Issue related to DIND:
https://github.com/docker-library/docker/issues/463
https://github.com/docker-library/docker/pull/468#issuecomment-1878086606

refs #000: fix dind for containeros 105

---

scripts/src/functions.bash
templates/.gitlab-ci-template.yml

This is a way to sleep pipeline jobs before running for debugging purposes.
It works by setting the following variables:
1. `DEBUG_JOB_SLEEP`: boolean
2. `DEBUG_JOB_SLEEP_JOB_NAME`: $CI_JOB_NAME_SLUG
3. `DEBUG_JOB_SLEEP_SECONDS`: seconds (optional)

feat: add a simple way to sleep jobs for debugging

---

Dockerfile

Enhancement
___
- Added the `mysql-client` package to the Docker image
- This enhancement allows for MySQL database operations directly from the container
- The change is made in the `RUN` instruction of the Dockerfile
- Other existing package installations and configurations remain unchanged
___
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Add MySQL client to Docker image</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Dockerfile
<li>Added <code>mysql-client</code> package to the …

feat: add mysql-client package

---

scripts/helm-init

Enhancement
___
- Modified the `scripts/helm-init` file to address helm warnings
- Added a `chmod 600 $KUBECONFIG || true` command before initializing helm
- This change sets the correct permissions on the KUBECONFIG file, which should suppress related warnings
- The `|| true` ensures the script continues even if the chmod command fails
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>helm-init</strong><dd><code>Adjust KUBECONFIG permissions to suppress warnings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
scripts/helm-init
<li>Added chmod command to change permissions of KUBECONFIG file to 600<br> <li> This change is made …

feat: suppress helm warnings

---

templates/.gitlab-ci-template.yml

internal #3202
___
Enhancement
___
- Implemented GCP Artifact Registry proxy for Docker:
- Added a new registry mirror pointing to a local proxy (127.0.0.1:5000)
- Configured Docker to accept insecure connections to the local proxy
- Introduced a new service `gcp-artifact-registry-docker-proxy`:
- Set up to proxy requests to GCP Artifact Registry (europe-west1-docker.pkg.dev)
- Listens on 0.0.0.0:5000 to serve Docker registry requests
- These changes aim to improve Docker image pulling performance and provide a centralized cache for container images
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>.gitlab-ci-template.yml</strong><dd><code>Configure GCP …

feat: gcp artifact registry proxy

---

templates/.gitlab-ci-template.yml

Enhancement
___
- Reordered Docker registry mirrors to prioritize local mirror over Google Container Registry (GCR) mirror
- Changed the order of `--registry-mirror` options in the Docker service configuration
- This change aims to improve Docker image pull performance by prioritizing the local mirror
- No other changes were made to the configuration or functionality
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>.gitlab-ci-template.yml</strong><dd><code>Optimize Docker registry mirror order</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …

change mirror order

---

templates/.gitlab-ci-template.yml

Enhancement
___
- Improved readability of the GitLab CI template by adding a missing comma in the service configuration.
- Enhanced the clarity of the debug sleep condition by changing the order of comparison in the if statement.
- The changes make the code more consistent and easier to understand without altering the functionality.
___
<tr>
<td>
<details>
<summary><strong>.gitlab-ci-template.yml</strong><dd><code>Enhance GitLab CI template readability and logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/.gitlab-ci-template.yml
<li>Added a comma at the end of the "--listen=0.0.0.0:5000" line in the …

feat: change compare order in if to make condition more clear

---

Dockerfile

Enhancement
___
- Added kube-linter (version 0.6.8) to the Docker image for Kubernetes manifest linting
- Introduced a multi-stage build to compile kube-linter from source
- Copied the kube-linter binary from the build stage to the final image
- Set proper permissions for the kube-linter binary
- Maintained existing functionality and versions of other tools in the image
___
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Add kube-linter to the Docker image</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

feat: add kube-linter binary

---

templates/.gitlab-ci-template.yml

Enhancement
___
- Improved Docker configuration file management in the GitLab CI template
- Added support for custom home directories using the `${HOME}` environment variable
- Enhanced error handling for directory creation and file copying
- Increased flexibility and portability of the Docker configuration process
- Maintained backwards compatibility with existing setup
___
<tr>
<td>
<details>
<summary><strong>.gitlab-ci-template.yml</strong><dd><code>Enhance Docker config file handling in CI template</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/.gitlab-ci-template.yml
<li>Improved Docker configuration file …

refs platform/#3233: improve docker config file management

---

scripts/src/functions.bash

Enhancement
___
- Enhanced Kubernetes context setup to always set a namespace, using 'default' as fallback when KUBE_NAMESPACE is not defined
- Simplified code by removing conditional check and using parameter expansion with default value
- Improved robustness of GitLab agent setup by ensuring namespace is always configured
___
<tr>
<td>
<details>
<summary><strong>functions.bash</strong><dd><code>Enforce default namespace in Kubernetes context setup</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
scripts/src/functions.bash
<li>Modified <code>_setup-gitlab-agent-kubernetes-context</code> function to always set <br>namespace<br> <li> Removed …

refs platform/#3231: enforce the set of the default namespace for the current context if the KUBE_NAMESPACE variable is not defined

---

templates/.gitlab-ci-template.yml

Enhancement, Configuration changes
___
- Introduced configurable variables for both default and docker-mirror images in GitLab CI template
- Added ability to override image configuration through project-specific `.gitlab-ci.yml` files
- Replaced hardcoded image references with variable interpolation:
- Default image: `${DEFAULT_IMAGE_REGISTRY}/${DEFAULT_IMAGE_REPOSITORY}:${DEFAULT_IMAGE_TAG}`
- Docker mirror: `${DOCKER_MIRROR_IMAGE_REGISTRY}/${DOCKER_MIRROR_IMAGE_REPOSITORY}:${DOCKER_MIRROR_IMAGE_TAG}`
- Default values maintain current behavior using `ghcr.io` registry
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details> …

refs platform/#2862: add variable to change the image configuration for the default image and for the docker mirror image

---

templates/.gitlab-ci-template.yml

Enhancement
___
- Renamed the Docker mirror service alias from `docker-mirror` to `docker-proxy` for better clarity
- Updated all related configuration variables from DOCKER_MIRROR to DOCKER_PROXY (registry, repository, and tag)
- Modified service configuration to use new proxy naming in commands and registry URLs
- Updated diagnostic section names and messages in testing scripts to reflect new terminology
___
<tr>
<td>
<details>
<summary><strong>.gitlab-ci-template.yml</strong><dd><code>Rename docker-mirror service and variables to docker-proxy</code></dd></summary>
<hr>
templates/.gitlab-ci-template.yml
<li>Renamed docker service from …

platform/#2862: change docker-mirror to docker-proxy and variables accordingly

---

Dockerfile
Makefile

Enhancement
___
- Updated Google Cloud CLI image tag to `504.0.0-alpine` in both Dockerfile and Makefile
- Updated Golang base image to version `1.23.4` in Dockerfile
- Ensures consistent and up-to-date dependencies across the project
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Update Google Cloud CLI and Golang base images</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Dockerfile
<li>Updated Google Cloud CLI image tag from <code>497.0.0-alpine</code> to <br><code>504.0.0-alpine</code><br> <li> Updated Golang base image from <code>1.23.0</code> to <code>1.23.4</code><br> …

Update gcloud to 504.0.0

---

templates/argocd/gitlab-ci-template-gitops-argo.yml

Enhancement
___
- Added functionality to remove namespace metadata from generated Helm manifests to allow ArgoCD to manage the target namespace
- Uses `yq` command to delete `.metadata.namespace` from all generated YAML/YML files
- This change enables better namespace management through ArgoCD deployment configuration
- Minor cleanup by removing trailing empty line
___
<tr>
<td>
<details>
<summary><strong>gitlab-ci-template-gitops-argo.yml</strong><dd><code>Remove namespace from Helm templates for ArgoCD management</code></dd></summary>
<hr>
templates/argocd/gitlab-ci-template-gitops-argo.yml
<li>Added command to remove namespace from generated manifests …

feat: remove namespace from templates generated with helm for ArgoCD deployments
